Repository tudo-aqua/stars, pull requests merged in 2024-05, with the labels that each got.

#91 Upgraded kotlin compiler version to v2.0.0-RC2.
  gradle/libs.versions.toml
Labels: performance

#90 Add DSL function for global monitors
  CHANGELOG.md
  stars-core/src/main/kotlin/tools/aqua/stars/core/tsc/builder/TSCBuilder.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/tsc/builder/TSCDsl.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/tsc/node/TSCBoundedNode.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/tsc/node/TSCNode.kt
Labels: feature

#96 Removed kover from GH workflow.
  .github/workflows/analyze-build-deploy.yml
Labels: documentation

#98 Unify default value KDoc documentation.
  stars-core/src/main/kotlin/tools/aqua/stars/core/evaluation/BinaryPredicate.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/evaluation/NullaryPredicate.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/evaluation/TSCEvaluation.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/evaluation/UnaryPredicate.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/tsc/TSCMonitorResult.kt
  stars-data-av/src/test/kotlin/tools/aqua/stars/data/av/TestHelperFunctions.kt
Labels: documentation

#99 Add try-finally block to runEvaluation() function to close all loggers.
  stars-core/src/main/kotlin/tools/aqua/stars/core/evaluation/TSCEvaluation.kt
Labels: performance, code-quality

#97 Add CITATION.cff file of EDCC paper
  CITATION.cff
Labels: documentation

#100 Unify CMFTBL operator documentation.
  stars-logic-kcmftbl/src/main/kotlin/tools/aqua/stars/logic/kcmftbl/eventually.kt
  stars-logic-kcmftbl/src/main/kotlin/tools/aqua/stars/logic/kcmftbl/globally.kt
  stars-logic-kcmftbl/src/main/kotlin/tools/aqua/stars/logic/kcmftbl/historically.kt
  stars-logic-kcmftbl/src/main/kotlin/tools/aqua/stars/logic/kcmftbl/maxPrevalence.kt
  stars-logic-kcmftbl/src/main/kotlin/tools/aqua/stars/logic/kcmftbl/minPrevalence.kt
  stars-logic-kcmftbl/src/main/kotlin/tools/aqua/stars/logic/kcmftbl/next.kt
  stars-logic-kcmftbl/src/main/kotlin/tools/aqua/stars/logic/kcmftbl/once.kt
  stars-logic-kcmftbl/src/main/kotlin/tools/aqua/stars/logic/kcmftbl/previous.kt
  stars-logic-kcmftbl/src/main/kotlin/tools/aqua/stars/logic/kcmftbl/since.kt
  stars-logic-kcmftbl/src/main/kotlin/tools/aqua/stars/logic/kcmftbl/until.kt
Labels: documentation

#105 Add segment counter to evaluation.
  stars-core/src/main/kotlin/tools/aqua/stars/core/evaluation/TSCEvaluation.kt
Labels: documentation

#107 Replace "pre-commit" hook with "pre-push" hook.
  .githooks/pre-commit
  .githooks/pre-push
Labels: performance

#110 Create single TSCFailedMonitorInstance for each failed monitor.
  stars-core/src/main/kotlin/tools/aqua/stars/core/evaluation/TSCEvaluation.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/metric/metrics/postEvaluation/FailedMonitorsMetric.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/tsc/TSCFailedMonitorInstance.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/tsc/instance/TSCInstanceNode.kt
Labels: feature

#83 76 add designated tscmonitorresult for each failed monitor
  stars-core/src/main/kotlin/tools/aqua/stars/core/metric/metrics/postEvaluation/FailedMonitorsGroupedByTSCInstanceMetric.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/metric/metrics/postEvaluation/FailedMonitorsGroupedByTSCNodeMetric.kt
Labels: feature
