Repository tudo-aqua/stars, pull requests merged in 2024-08, with the labels that each got.

#143 Clean up project files
  HACKING.md
  codecov.yml
Labels: clean-up

#144 Prepare CHANGELOG.md and README.md for v0.4
  CHANGELOG.md
  README.md
Labels: release

#146 Update developer name
  build.gradle.kts
Labels: documentation

#152 Update dependabot.yml
  .github/dependabot.yml
Labels: dependencies

#157 Update detekt config file
  buildSrc/src/main/kotlin/tools.aqua.stars.library-conventions.gradle.kts
  contrib/detekt-rules.yml
  gradle/libs.versions.toml
Labels: code-quality

#154 Fix `println()` for TSCs
  CHANGELOG.md
  stars-core/src/main/kotlin/tools/aqua/stars/core/tsc/builder/TSCBoundedBuilder.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/tsc/node/TSCNode.kt
  stars-core/src/test/kotlin/tools/aqua/stars/core/tsc/TSCToStringTest.kt
Labels: bug

#164 Fix deletion of test-result-logs folders
  stars-core/src/main/kotlin/tools/aqua/stars/core/evaluation/TSCEvaluation.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/metric/providers/Loggable.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/metric/utils/ApplicationConstantsHolder.kt
Labels: bug

#167 Upgraded gradle to v8.10.
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#171 Added exception when adding a condition to the root node.
  CHANGELOG.md
  stars-core/src/main/kotlin/tools/aqua/stars/core/tsc/builder/TSCDsl.kt
  stars-core/src/test/kotlin/tools/aqua/stars/core/tsc/TSCDuplicatedLabelsTest.kt
  stars-core/src/test/kotlin/tools/aqua/stars/core/tsc/TSCRootTest.kt
Labels: bug
