Repository tudo-aqua/stars, pull requests merged in 2024-02, with the labels that each got.

#35 Replace old JVM Target with jvmToolchain
  buildSrc/src/main/kotlin/tools.aqua.stars.kotlin-conventions.gradle.kts
Labels: bug

#37 Clarify KDoc of FailedMonitorsMetric
  stars-core/src/main/kotlin/tools/aqua/stars/core/metric/metrics/postEvaluation/FailedMonitorsMetric.kt
Labels: documentation

#36 Remove all existing ego flags when useEveryVehicleAsEgo is set
  stars-importer-carla/src/main/kotlin/tools/aqua/stars/importer/carla/runSegmentation.kt
Labels: bug

#38 Add previous operator for two entities
  stars-logic-kcmftbl/src/main/kotlin/tools/aqua/stars/logic/kcmftbl/previous.kt
Labels: feature

#41 Updated GitHub workflow JDK to 17 (#40).
  .github/workflows/analyze-build-deploy.yml
Labels: performance

#39 Add additional checks for the primaryEntityId getter
  stars-data-av/src/main/kotlin/tools/aqua/stars/data/av/dataclasses/Segment.kt
  stars-data-av/src/test/kotlin/tools/aqua/stars/data/av/dataclasses/SegmentPrimaryEntityTest.kt
Labels: bug

#43 Add missing "evaluate" function call for PostEvaluationMetricProviders
  stars-core/src/main/kotlin/tools/aqua/stars/core/evaluation/TSCEvaluation.kt
Labels: bug

#45 Fix ProjectionMetrics skipping if all projections are valid or invalid (#44)
  stars-core/src/main/kotlin/tools/aqua/stars/core/metric/metrics/evaluation/InvalidTSCInstancesPerProjectionMetric.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/metric/metrics/evaluation/MissedTSCInstancesPerProjectionMetric.kt
Labels: bug

#49 Unified parameter naming in UnaryPredicate and BinaryPredicate.
  stars-core/src/main/kotlin/tools/aqua/stars/core/evaluation/BinaryPredicate.kt
  stars-core/src/main/kotlin/tools/aqua/stars/core/evaluation/UnaryPredicate.kt
Labels: code-quality
